[package]
name = "flint-rs"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flint-sys = { path = "../flint-sys" }
gmp-mpfr-sys = "1.3.1"
rug = "1.10.0"
