[package]
name = "flint-rs"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]
edition = "2018"
links = "flint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
gmp-mpfr-sys = "1.3.1"

[build-dependencies]
bindgen = "0.53.1"
