[package]
name = "flint-sys"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]
edition = "2018"
links = "flint"
description = "Bindings to the FLINT C library"
homepage = "https://github.com/alex-ozdemir/flint-rs/flint-sys"
repository = "https://github.com/alex-ozdemir/flint-rs"
documentation = "https://doc.rs/flint-sys"
license = "MIT OR Apache-2.0"
keywords = ["polynomials", "number-theory", "math"]
categories = ["cryptography", "algorithms", "external-ffi-bindings"]
readme = "README.md"
exclude = [
    "benches",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
gmp-mpfr-sys = "1.3.1"
